### ISSUE TITLE
model output result is error

### ISSUE THREAD

**Issue by Evoluange** [kemaloksuz/RankSortLoss-Solov2#2] opened 2021-08-18 02:48 UTC
Hi,
I success to get pth model using your code.
Howerer, when I test the result using inference_solo.py 

`
from mmdet.apis import init_detector, inference_detector, show_result_pyplot, show_result_ins
import mmcv
import argparse
import os

parser = argparse.ArgumentParser(description='Solo test script')
parser.add_argument('--config', default=None, type=str, help='config_file')
parser.add_argument('--weight', default=None, type=str,
                    help='Checkpoint state_dict file to resume training from. If this is "interrupt')

parser.set_defaults(keep_latest=False, log=True, log_gpu=False, interrupt=True, autoscale=True)
args = parser.parse_args()

config_file = args.config
checkpoint_file = args.weight

imgPath = None

imgDir = r"./imgs"
outDir = r"./imgs-test"

model = init_detector(config_file, checkpoint_file, device='cuda:0')

for file in os.listdir(imgDir):
    imgPath = os.path.join(imgDir, file)
    result = inference_detector(model, imgPath)
    outPath = os.path.join(outDir, file.rsplit(".", 1)[0] + "_res.jpg")

    print(imgPath, "========>>", outPath)
    show_result_ins(imgPath, result, model.CLASSES, score_thr=0.25, out_file=outPath)
print(" end !!! ")
`

 python inference_solo.py --config=configs/ranksort_loss/ranksort_solov2_light_448_r34_fpn_3x.py --weight=work_dirs/ranksort_solov2_light_448_r34_fpn_3x/epoch_36.pth

I have not get any ouput result, the "./imgs-test" is empty, print(result) get None.
the result is correct when no use ranksortloss,
I guess it may be have some problem in code.

**Comment by kemaloksuz** [comment] 2021-08-21 12:05
Thanks for your notification. First, I have not validated show_result_ins, but only used the inference code to obtain AP values as explained in Readme file. Second, the code is very slightly different than the one that we conducted experiments. Even though they are minor changes, I have not reproduced the result with these minor modifications. I have temporarily released this repo to present the implementation on SOLOv2, and I got a feedback that it is working. Finally, upon your issue, I validated the NMS score threshold, which can trigger CUDA OUT OF MEMORY error during inference. So, it may also cause your issue. Fixed configs are pushed now.

I will reproduce the results with this repo as well soon, but I cannot promise a date now. You can retry it with the new configs. Maybe you can try to test on COCO minival as explained in readme to see if it is working after one epoch of training instead of waiting for 36 epochs if you are keen to reproduce the results. If you have some positive results after the first epoch, then you can let it run for 36 epochs. Please use 16 images on 4 GPUS (4 images/GPU) for ResNet101 and 32 images on 4 GPUs (8 images/GPU) for ResNet34.

**Comment by Evoluange** [comment] 2021-08-21 13:29
Thank you for your reply.
I was not train RankSortLoss model in your repo but in https://github.com/WXinlong/SOLO, because of install error when run "pip install -v -e ." and  I don't know why .
So I copy you modified code in the repo and run success use coco data but model output result  is none.
I will retry it with your new configs.
Thanks again !

**Comment by kemaloksuz** [comment] 2021-08-25 20:39
I have updated the installation documentation (https://github.com/kemaloksuz/RankSortLoss-Solov2/blob/master/docs/INSTALL.md). There should not be any problem with the installation of the repo since I could successfully install this repo from scratch today to test it again. If you are still interested, please try to install this repo and let me know if you have problems.

**Comment by kemaloksuz** [comment] 2021-08-29 12:51
Recently, I have reproduced the results and there should not be any problem with the repo. That's why, I am closing this issue. Please open a new issue if you still have problem.

**Closed as completed by kemaloksuz** 2021-08-29 12:51 UTC
